server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/v1/posts/**

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/v1/comments/**

        - id: reaction-service
          uri: lb://reaction-service
          predicates:
            - Path=/api/v1/reactions/**

        - id: user-relation-service
          uri: lb://user-relation-service
          predicates:
            - Path=/api/v1/user-relations/**

        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/api/v1/media/**

gateway:
  restricted-paths:
    - ^/api/v1/.*/internal/.*
    - ^/actuator/.*

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}